FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY app.js /usr/share/nginx/html/app.js
COPY ptt.js ptt-history.js /usr/share/nginx/html/
COPY styles.css /usr/share/nginx/html/styles.css
